### ISSUE TITLE
support of sparsed Matrix output of alevin

### ISSUE THREAD

**Issue by DrHogart** [mikelove/fishpond#1]
Hi,
Currently the default output of `salmon alevin` is sparsed Matrix, but fishpond can deal only with regular matrix. E.g. trying to apply of `scaleInfReps` (v. 1.3.10) to `salmon alevin` (v.1.1.0) output file results to this:

```{r}
Error in colSums(counts) :
  'x' must be an array of at least two dimensions
```

**Comment by mikelove** [comment]
Thanks — I’ll address this tonight.

**Comment by mikelove** [comment]
Thanks again for posting the issue, I think I've addressed this here:

c8d02c27c5af5f9a32951443c2f43b8e9fd2a068

In particular, I changed `labelKeep` so it can be run on sparse matrices, and then added code to the vignette to clarify how and when to make the matrices dense.

https://github.com/mikelove/fishpond/blob/master/vignettes/swish.Rmd#L742-L748

`swish` needs to compute ranks which currently makes the matrices not sparse, but the above should work for testing two groups of cells across a subset of expressed genes, which shouldn't be too large of a "cube" of data.

**Comment by DrHogart** [comment]
Thank you for the quick commit, it works on my data.

**Comment by mikelove** [comment]
Out of curiosity, how large of data are you interested in testing, eg how many genes passing filtering (minimal expression) and how many cells at a time?

Also make sure to update tximport to >= 1.4.2.

We had a bug in importing inf reps but we pushed a fix.

**Comment by DrHogart** [comment]
My data actually is the sample- and UMI-barcoded bulk RNA-seq, so the number of samples (aka cells) is not huge, less than 50; there are 6000-8000 genes passing filters in each sample.
My tximport is 1.14.2

**Comment by mikelove** [comment]
Got it. Thanks. Shouldn’t be a problem converting to dense. It can get slow with ~1,000 of cells and all ~50,000 genes.

Oops i meant 1.14.2.
