### ISSUE TITLE
plotInfReps y axis mislabel

### ISSUE THREAD

**Issue by qxxxd** [mikelove/fishpond#16]
Hello,

  First I want to thank you for the great package!

  When I was trying to plot the expression of transcripts using `plotInfReps`, I noticed that the y axis label was 'counts' in stead of 'scaled counts' by default although I've run `scaleInfReps` already in the first step. I guess this was due to a mistyped "infRepsScaled" in these lines?

https://github.com/mikelove/fishpond/blob/ca8c3f6b77b20991bcbd5de90a186544df3871a6/R/helper.R#L160-L163

**Comment by mikelove** [comment]
Thanks for the catch! Just pushed this to Bioc and GitHub.

**Comment by mikelove** [comment]
If you see anything else, or have questions about interpretation of results, feel free to post here or on Bioc support site, whichever you prefer.
