### ISSUE TITLE
R CMD check WARNING: Requires (indirectly) orphaned package: ‘gtools’ 

### ISSUE THREAD

**Issue by DongzeHE** [mikelove/fishpond#26]
Hello @mikelove,

I got a warning when doing R CMD check for the `roe` package saying that an orphaned package is indirectly required. `gtools` is a dependency in `fishpond`. 
```
  ❯ checking package dependencies ... WARNING
  Requires (indirectly) orphaned package: ‘gtools’
```
I think this happened very recently because I did not see this warning last month. The only effect is that this warning made my github actions unhappy :(.

In the [package's webpage](https://cran.r-project.org/web/packages/gtools/index.html), it shows that the maintainer is ORPHANED. 

```
Version: | 3.9.2.2
-- | --
Depends: | R (≥ 2.10), methods, stats, utils
Suggests: | car, gplots, knitr, rstudioapi, SGP, taxize
Published: | 2022-06-13
Author: | Gregory R. Warnes, Ben Bolker, Thomas Lumley and CRAN team
Maintainer: | ORPHANED
``` 

Just want to report this. As `gools` is a widely used package, maybe someone will take the maintainership soon. 

Dongze

**Comment by mikelove** [comment]
Interesting. We have a key function gtools::permutations() that we use in swish(). I likewise think it would be picked up soon bc it is broadly used…

**Comment by mikelove** [comment]
For now maybe ignore the warning?

https://stackoverflow.com/a/72226230
