### ISSUE TITLE
Error in dbFileConnect(file)

### ISSUE THREAD

**Issue by sunliang3361** [mikelove/fishpond#3]
Hi,
When I try to run your sample code and data, I found the following error messages, do you know what my problem is? I can successfully load all required R packages. Thank you

-------error message below_---------

> suppressPackageStartupMessages(library(SummarizedExperiment))
> se <- tximeta(coldata)
importing quantifications
reading in files with read_tsv
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 
found matching transcriptome:
[ Gencode - Homo sapiens - release 29 ]
loading existing TxDb created: 2020-06-05 21:23:05
Error in dbFileConnect(file) : 
  DB file '/Users/xxx/Library/Caches/BiocFileCache/13d2eae3fb0a_13d2eae3fb0a.sqlite' not found

**Comment by sunliang3361** [comment]
These are all codes:
library(tximeta)
library(fishpond)
library(macrophage)

#library(swish)

dir <- system.file("extdata", package="macrophage")
coldata <- read.csv(file.path(dir, "coldata.csv"))
coldata <- coldata[,c(1,2,3,5)]
names(coldata) <- c("names","id","line","condition")
coldata$files <- file.path(dir, "quants", coldata$names, "quant.sf.gz")
all(file.exists(coldata$files))

suppressPackageStartupMessages(library(SummarizedExperiment))

se <- tximeta(coldata)

**Comment by mikelove** [comment]
This is actually a `tximeta` issue, so maybe you can post either on that GitHub or on support.bioconductor.org if the following link doesn't help:

https://bioconductor.org/packages/release/bioc/vignettes/tximeta/inst/doc/tximeta.html#errors_connecting_to_a_database

What happened is that the files in the cache were removed but not by BiocFileCache which manages the cache directory. So BiocFileCache throws an error when the file it expects to be present is not.
