### ISSUE TITLE
Have all 0 LFC for all infReps, remove these first

### ISSUE THREAD

**Issue by zhangjy859** [mikelove/fishpond#36]
Hi, 

I got a error when `test dynamic allelic imbalance`, 

```
y <- swish(y, x="allele", pair="samples",
           cov="time", cor="pearson")
```

```
Error in swishCorPair(infRepsArray, condition, pair, covariate, cor, nperms,  : 
  5220 features have all 0 LFC for all infReps, remove these first
```

However, I am not sure how to remove all 0 LFC for all infReps, could you please give me more infomation?

Regrads,

Zhang

**Comment by mikelove** [comment]
You can use the labelKeep function… see vignette.

**Comment by zhangjy859** [comment]
Hi, 

I noted that, and I have run 
```
y <- labelKeep(y)
y <- y[mcols(y)$keep,]
```

**Comment by zhangjy859** [comment]
My full code is: 

```
y <- importAllelicCounts(
  sample_tximeta, a1="L", a2="R",
  format="wide", tx2gene=tx2gene.1
)
y <- labelKeep(y)
y <- y[mcols(y)$keep,]

y <- fishpond::swish(y, x="allele", pair="samples",
           cov="time", cor="pearson")
```

**Comment by mikelove** [comment]
Oh right. I forgot the right code to use.

See this code chunk

https://thelovelab.github.io/fishpond/articles/allelic.html#filtering-features

**Comment by zhangjy859** [comment]
Hi, 

Its work well, thank you for your help

Regrads, 

Zhang
