### ISSUE TITLE
Unused argument (diffAI = TRUE)

### ISSUE THREAD

**Issue by zhangjy859** [mikelove/fishpond#37]
Hi, 

I am trying to create a stimulation data following the guide, but I got a error:

```
library(fishpond)
set.seed(1)
y <- makeSimSwishData(diffAI=TRUE, n=12)
colData(y)

Error in makeSimSwishData(diffAI = TRUE, n = 12) : 
  unused argument (diffAI = TRUE)
```

I think it's because the version of fishpond seems too old (2.2.0), but this seems to be the latest version in `BiocManager` on the Windows platform?

Regrads.

Zhang

**Comment by mikelove** [comment]
Check the man page from R. If you don’t see the argument it indicates you may have an older version.

**Comment by mikelove** [comment]
Sorry, didn’t see your update.

The version of Bioc package delivered depends on your version of R.

**Comment by zhangjy859** [comment]
Hi @mikelove,

Thank you for your prompt reply. My R version is 4.2.1, which doesn't seem to be an outdated version. Is it possible to add support for this R version in the new version?

I successfully created example data in other versions of R. Can I confirm with you about the `pair` parameter in `swish`? I am not a method or statistical expert. Based on my understanding of your well written paper, code and examples (my understanding may not be correct), for allelic different analysis, the `pair` here actually refers to the pairing of two alleles (a1 and a2), not the pairing of samples under two conditions (for example, sample A before and after receiving a certain treatment).

**Comment by mikelove** [comment]
It’s not possible to change the Bioc installation script. But you can see how to get the latest version here:

https://www.bioconductor.org/install/

yes, we use pair in the AI examples to indicate pairing of the two alleles within a donor.

**Comment by zhangjy859** [comment]
Hi @mikelove 

Thank you so much for your prompt response to my question! I truly appreciate your efficiency and professionalism. 

I will close this issue, once again, thank you for your dedication and support!
